### ISSUE TITLE
उ॒दा॒हर॑णादिषु सूत्रसङ्ख्याव्यत्य॒यः

### ISSUE THREAD

**Issue by ujjvlh** [ashtadhyayi/ashtadhyayi.github.io#37]
या स॒त्या सू॑त्रसङ्ख्या॒ यथा॑ [ashtadhyayi.com/sutraani/](https://ashtadhyayi.com/sutraani/) इत्यत्र॑ ल॒भ्यते॒ तस्याः॒ स्थान॑ ए॒वं सू॑त्रस॒ङ्ख्या परि॑वर्तिता क॒थञ्चि॑द् भा॒ष्ये॑षु-

[स॒त्याध्या॑यस॒ङ्ख्या].[स॒त्या पा॑दस॒ङ्ख्या].[अस॑त्या सूत्रस॒ङ्ख्या, पा॑दस॒ङ्ख्यया॑ स॒मा]

यथा॑ ७.२.११६ इत्य॒स्य स्थाने॑ ७.२.२

**Comment by vvasuki** [comment]
सूचनयोपकृतः। https://github.com/ashtadhyayi/ashtadhyayi.github.io/commit/ac361021c0b1d147c99717a6608976752f8d1fed इत्यनेन परिहृतम्।
