### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by vvasuki** [ashtadhyayi/ashtadhyayi.github.io#8]
Added list pages like: https://ashtadhyayi.github.io/ui/vritti/kashika/

**Comment by vvasuki** [comment]
Main UI is broken. Investigating.

**Comment by vvasuki** [comment]
Moved the repository, and begun using the main page for sUtra list. Individual vritti pages are no longer being generated due to https://github.com/ashtadhyayi/ashtadhyayi.github.io/issues/9 (besides, they're probably not that useful).

@chandrasekharanr Please move your links to https://ashtadhyayi.github.io/sutra-details/?sutra=1.1.1 from https://ashtadhyayi.github.io/ui/?sutra=1.1.1 . Right now, I've kept the /ui/ url to avoid problems to users, but I would like to remove it entirely.

**Comment by chandrasekharanr** [comment]
This is done. Can you please close this issue @vvasuki ?
